const birds = [
  { kanji: "鷺", yomi: "さぎ" },
  { kanji: "鷹", yomi: "たか" },
  { kanji: "鶴", yomi: "つる" },
  { kanji: "燕", yomi: "つばめ" },
  { kanji: "鷂", yomi: "はいたか" },
  { kanji: "鳶", yomi: "とんび" },
  { kanji: "鷲", yomi: "わし" },
  { kanji: "烏", yomi: "からす" },
  { kanji: "鳳凰", yomi: "ほうおう" },
  { kanji: "鷦鷯", yomi: "みそさざい" },
  { kanji: "鶉", yomi: "うずら" },
  { kanji: "鶯", yomi: "うぐいす" },
  { kanji: "朱鷺", yomi: "とき" },
  { kanji: "鵲", yomi: "かささぎ" },
  { kanji: "梟", yomi: "ふくろう" },
  { kanji: "雉", yomi: "きじ" },
  { kanji: "鵜", yomi: "う" },
  { kanji: "鶚", yomi: "みさご" },
  { kanji: "翡翠", yomi: "かわせみ" },
  { kanji: "鴨", yomi: "かも" },
  { kanji: "孔雀", yomi: "くじゃく" },
  { kanji: "鵯", yomi: "ひよどり" },
  { kanji: "鸚鵡", yomi: "おうむ" },
  { kanji: "鸚哥", yomi: "いんこ" },
  { kanji: "啄木鳥", yomi: "きつつき" },
  { kanji: "鸛", yomi: "こうのとり" },
  { kanji: "郭公", yomi: "かっこう" },
  { kanji: "雀", yomi: "すずめ" },
  { kanji: "駝鳥", yomi: "だちょう" },
  { kanji: "鶫", yomi: "つぐみ" },
  { kanji: "隼", yomi: "はやぶさ" },
  { kanji: "葦雀", yomi: "よしきり" },
  { kanji: "鶸", yomi: "ひわ" },
  { kanji: "雲雀", yomi: "ひばり" },
  { kanji: "信天翁", yomi: "あほうどり" },
];

export { birds };
