const countries = [
  { kanji: "亜米利加", yomi: "アメリカ" },
  { kanji: "英吉利", yomi: "イギリス" },
  { kanji: "伯剌西爾", yomi: "ブラジル" },
  { kanji: "埃及", yomi: "エジプト" },
  { kanji: "葡萄牙", yomi: "ポルトガル" },
  { kanji: "伊色剌", yomi: "イスラエル" },
  { kanji: "伊太利", yomi: "イタリア" },
  { kanji: "西班牙", yomi: "スペイン" },
  { kanji: "濠太剌利", yomi: "オーストラリア" },
  { kanji: "墺太利", yomi: "オーストリア" },
  { kanji: "阿蘭陀", yomi: "オランダ" },
  { kanji: "蘇格蘭", yomi: "スコットランド" },
  { kanji: "新西蘭", yomi: "ニュージーランド" },
  { kanji: "波蘭", yomi: "ポーランド" },
  { kanji: "義蘭", yomi: "イラン" },
  { kanji: "烏克蘭", yomi: "ウクライナ" },
  { kanji: "芬蘭", yomi: "フィンランド" },
  { kanji: "錫蘭", yomi: "スリランカ" },
  { kanji: "希臘", yomi: "ギリシャ" },
  { kanji: "土耳古", yomi: "トルコ" },
  { kanji: "諾威", yomi: "ノルウェー" },
  { kanji: "仏蘭西", yomi: "フランス" },
  { kanji: "盧森堡", yomi: "ルクセンブルク" },
  { kanji: "緬甸", yomi: "ミャンマー" },
  { kanji: "黎巴嫩", yomi: "レバノン" },
];

export { countries };

// {
//     link:"/",
//     title:"",
//     myClass: "cat flowers",
//     score: 0,
//   },
