const insects = [
  { kanji: "蜘蛛", yomi: "くも" },
  { kanji: "螻蛄", yomi: "けら" },
  { kanji: "蝶", yomi: "ちょう" },
  { kanji: "蛞蝓", yomi: "なめくじ" },
  { kanji: "蝸牛", yomi: "かたつむり" },
  { kanji: "蜈蚣", yomi: "むかで" },
  { kanji: "蜚蠊", yomi: "ごきぶり" },
  { kanji: "蛾", yomi: "が" },
  { kanji: "蚊", yomi: "か" },
  { kanji: "飛蝗", yomi: "ばった" },
  { kanji: "蜻蛉", yomi: "とんぼ" },
  { kanji: "蟷螂", yomi: "かまきり" },
  { kanji: "蜩", yomi: "ひぐらし" },
  { kanji: "蠶", yomi: "かいこ" },
  { kanji: "蛭", yomi: "ひる" },
  { kanji: "蟻", yomi: "あり" },
  { kanji: "蛍", yomi: "ほたる" },
  { kanji: "蝉", yomi: "せみ" },
  { kanji: "蚤", yomi: "のみ" },
  { kanji: "瓢虫", yomi: "てんとうむし" },
  { kanji: "蚯蚓", yomi: "みみず" },
  { kanji: "馬陸", yomi: "やすで" },
  { kanji: "蛆", yomi: "うじ" },
  { kanji: "蟋蟀", yomi: "こおろぎ" },
  { kanji: "螽斯", yomi: "きりぎりす" },
  { kanji: "蠍", yomi: "さそり" },
];

export { insects };
